run:
  dataset: massive_domain
  scale: small
  llm_triplet:  llama3.2:3b-instruct-q8_0
  llm_pairs:  llama3.2:3b-instruct-q8_0
  seed: 42

run2llms:
  dataset: massive_domain
  scale: small
  llm_triplet: llama3.2:3b-instruct-q8_0
  llm_pairs: llama3.2:3b-instruct-q8_0
  seed: 42

datasets:
  all:
    - bank77
    - clinc150
    - massive_intent
    - massive_domain
    - mtop_intent
    - mtop_domain
    - go_emotions
    - reddit
    - stackex
    - arxiv
    - few_event
    - few_nerd_nat
    - few_rel_nat
    - clinc_intent
    - clinc_domain