#!/usr/bin/env bash
set -euo pipefail

# 1. Project Root and Environment
REPO_ROOT="/home/hamadygackou777/clusterllm-local"
export PYTHONPATH="${REPO_ROOT}/src:${PYTHONPATH:-}"

# 2. Working Directory
cd "${REPO_ROOT}/src/clusterllm/granularity"

echo "================================================================"
echo "🚀 GENERATING PAIRS FOR GRANULARITY ANALYSIS"
echo "================================================================"

# 3. Variables - POINTING TO YOUR FINE-TUNED DATA
DATA_PATH="${REPO_ROOT}/datasets/banking77/test.jsonl"
# Using the embeddings generated by your finetuned model
# Change .hdf5 to .h5 to match your actual file
FEAT_PATH="${REPO_ROOT}/datasets/banking77/embeddings_finetuned.h5"

# 4. Execution
# We use the arguments defined in your Python code: --dataset, --data_path, --feat_path, etc.
python sample_pairs.py \
    --dataset "banking77" \
    --data_path "$DATA_PATH" \
    --feat_path "$FEAT_PATH" \
    --embed_method "finetuned" \
    --scale "small" \
    --k 1 \
    --min_clusters 2 \
    --max_clusters 200 \
    --out_dir "sampled_pair_results" \
    --seed 100

echo "✅ Pair sampling complete. Results saved in granularity/sampled_pair_results/"