#!/usr/bin/env bash
set -euo pipefail

# 1. Project Root and Environment
REPO_ROOT="/home/hamadygackou777/clusterllm-local"
GRAN_DIR="${REPO_ROOT}/src/clusterllm/granularity"

export PYTHONPATH="${REPO_ROOT}/src:${PYTHONPATH:-}"

# 2. Working Directory Check
if [ -d "$GRAN_DIR" ]; then
    cd "$GRAN_DIR"
    echo "📍 Working directory: $PWD"
else
    echo "❌ ERROR: Directory $GRAN_DIR does not exist."
    exit 1
fi

# 3. Variables
# This is the destination file for the prompt configuration
prompt_path="prompts_pair_exps_pair_v8.json"

for dataset in "banking77"
do
    echo "--- Processing: $dataset ---"
    
    # Path to the file generated by your successful sample_pairs.sh
    sampled_pair_path="${GRAN_DIR}/sampled_pair_results/${dataset}_embed=finetuned_s=small_k=1_multigran2-200_seed=100.json"
    data_path="${REPO_ROOT}/datasets/${dataset}/test.jsonl"

    # Safety checks
    if [ ! -f "$sampled_pair_path" ]; then
        echo "❌ ERROR: Sampled pair file not found at: $sampled_pair_path"
        continue
    fi

    if [ ! -f "$data_path" ]; then
        echo "❌ ERROR: Data file not found at: $data_path"
        continue
    fi

    # 4. Execution
    # num_sampled 16: Total candidate pairs to consider [cite: 277]
    # num_for_prompt 2: Number of Yes/No examples to show the LLM [cite: 172, 536]
    python sample_pairs_for_prompt.py \
        --prompt_path "$prompt_path" \
        --sampled_pair_path "$sampled_pair_path" \
        --data_path "$data_path" \
        --dataset "$dataset" \
        --num_sampled 16 \
        --num_for_prompt 2 \
        --seed 1234
done

echo "✅ Few-shot prompt preparation complete."